const common = {
	stock: 100,
	certifications: ["GMP Certified", "Lab Tested", "Made in India"],
	claims: ["Pure Ayurvedic Extracts", "Non-Habit Forming", "No Added Sugar", "Quality Tested"],
	prepaidOffer: "Get an extra 10% off on prepaid orders",
	safetyNotice: "Consult your physician before use if you are pregnant, nursing, have a medical condition, or take prescription medication. Keep out of reach of children.",
	faqs: [
		{ question: "How long until I see results?", answer: "Results vary by person. Most customers assess the product after 3–4 weeks of consistent daily use." },
		{ question: "How should I store it?", answer: "Store in a cool, dry place away from direct sunlight and keep the container tightly closed." },
		{ question: "Is Cash on Delivery available?", answer: "Yes, Cash on Delivery is available for eligible Indian pin codes." },
		{ question: "What is the return policy?", answer: "Unopened products may be returned within 7 days of delivery. Contact support to start a return." },
	],
	commitmentParagraph: "Every batch is checked for identity, purity, and consistency. We use transparent labels and carefully sourced botanicals so your daily wellness routine is simple and dependable.",
};

export const products = [
	{
		...common,
		id: "liver-care-capsules",
		title: "Liver Care Capsules",
		category: "Capsules",
		concern: "Liver & Digestion",
		description: "A focused Ayurvedic blend created to support liver function and comfortable digestion.",
		longDescription: "A daily botanical formula combining classical liver-supporting herbs in an easy capsule format.",
		price: 1199,
		badge: "Best Seller",
		priceLabel: "Inclusive of all taxes",
		tagline: "Daily botanical support for digestion and liver wellness",
		quantity: "60 Capsules",
		dosage: "Take 1–2 capsules twice daily after meals with water.",
		suitableFor: "Adults",
		images: [{ url: "/assets/img/p-1.jpeg" }, { url: "/assets/img/pe-1.png" }, { url: "/assets/img/ingredients.png" }],
		ingredients: [
			{ name: "Kutki", amount: "200 mg", benefit: "Traditionally used to support healthy liver function", image: "/assets/img/ingredients.png" },
			{ name: "Bhumi Amla", amount: "200 mg", benefit: "Supports digestion and antioxidant defenses", image: "/assets/img/story.png" },
			{ name: "Kalmegh", amount: "150 mg", benefit: "Helps maintain digestive comfort", image: "/assets/img/method.png" },
		],
		benefits: ["Supports healthy liver function", "Promotes comfortable digestion", "Supports natural detoxification"],
		keyBenefits: [
			{ title: "Liver Support", description: "Botanicals selected to support normal liver function." },
			{ title: "Better Digestion", description: "Helps maintain digestive comfort after meals." },
			{ title: "Daily Balance", description: "Designed for a simple, consistent wellness routine." },
		],
		pricingTiers: [
			{ bottles: 1, duration: "1 Month", price: 699 },
			{ bottles: 2, duration: "2 Months", price: 1199, originalPrice: 1398, badge: "Best Value" },
			{ bottles: 3, duration: "3 Months", price: 1699, originalPrice: 2097 },
		],
		aboutParagraphs: ["Liver Care Capsules bring time-tested Ayurvedic herbs into a practical daily format.", "The formula is made in small, quality-controlled batches for reliable consistency."],
		benefitsIntro: "Each botanical plays a complementary role in supporting liver function, digestion, and everyday metabolic wellness.",
		ingredientsIntro: "A concise blend of classical Ayurvedic herbs chosen for their traditional roles in liver and digestive care.",
		howItWorks: "The formula supports digestion and the body's natural metabolic processes through consistent daily use.",
		productDetails: ["Vegetarian capsules", "No added sugar", "Made in a GMP-certified facility", "60 capsules per bottle"],
		usageLevels: [{ label: "Daily Support", tablets: 1, frequency: "Twice daily after meals" }, { label: "Intensive Routine", tablets: 2, frequency: "Twice daily after meals" }],
		testimonialsIntro: "Customers share how the formula fits into their everyday wellness routine.",
		testimonials: [{ name: "Aarav S.", role: "Verified customer", quote: "Easy to add to my routine, and I feel lighter after meals.", image: "/assets/img/p-4.jpeg" }, { name: "Meera K.", role: "Verified customer", quote: "The dosage is straightforward and the packaging feels premium.", image: "/assets/img/p-5.jpeg" }],
		relatedIds: ["ashwagandha-capsules", "amla-aloe-juice"],
	},
	{
		...common,
		id: "ashwagandha-capsules",
		title: "Ashwagandha Capsules",
		category: "Capsules",
		concern: "Stress & Vitality",
		description: "Standardized Ashwagandha root extract for calm energy, resilience, and restful sleep.",
		longDescription: "A convenient daily adaptogen formulated to support the body's response to everyday stress.",
		price: 899,
		badge: "Popular",
		tagline: "Calm focus and steady vitality, every day",
		quantity: "60 Capsules",
		dosage: "Take 1 capsule once or twice daily after food.",
		suitableFor: "Adults managing everyday stress",
		images: [{ url: "/assets/img/p-2.jpeg" }, { url: "/assets/img/pe-4.png" }, { url: "/assets/img/caps-all.png" }],
		ingredients: [{ name: "Ashwagandha Root Extract", amount: "500 mg", benefit: "Supports stress adaptation and vitality", image: "/assets/img/ingredients.png" }],
		benefits: ["Supports calm energy", "Promotes restful sleep", "Helps maintain focus"],
		keyBenefits: [{ title: "Stress Support", description: "Helps the body adapt to everyday stress." }, { title: "Restful Sleep", description: "Supports healthy sleep quality." }, { title: "Steady Energy", description: "Promotes balanced vitality without stimulants." }],
		pricingTiers: [{ bottles: 1, duration: "1 Month", price: 499 }, { bottles: 2, duration: "2 Months", price: 899, originalPrice: 998, badge: "Best Value" }, { bottles: 3, duration: "3 Months", price: 1299, originalPrice: 1497 }],
		aboutParagraphs: ["Ashwagandha has a long history of use in Ayurveda as a restorative adaptogen.", "This standardized capsule makes consistent daily use simple."],
		benefitsIntro: "A single-herb formula designed for calm focus, recovery, and sustainable energy.",
		ingredientsIntro: "Made with standardized Ashwagandha root extract for consistent potency.",
		howItWorks: "Ashwagandha supports the body's natural stress response and helps maintain balanced energy.",
		productDetails: ["Standardized root extract", "Vegetarian capsules", "Stimulant free", "60 capsules per bottle"],
		usageLevels: [{ label: "Daily Balance", tablets: 1, frequency: "Once daily after food" }, { label: "Extra Support", tablets: 1, frequency: "Twice daily after food" }],
		testimonialsIntro: "Real feedback from customers building calmer daily routines.",
		testimonials: [{ name: "Rohan P.", role: "Verified customer", quote: "It has become an easy part of my evening routine.", image: "/assets/img/p-6.jpeg" }],
		relatedIds: ["liver-care-capsules", "amla-aloe-juice"],
	},
	{
		...common,
		id: "amla-aloe-juice",
		title: "Amla Aloe Juice",
		category: "Juices",
		concern: "Immunity & Digestion",
		description: "A refreshing Amla and Aloe Vera blend for daily digestive and antioxidant support.",
		longDescription: "A convenient botanical juice combining two familiar Ayurvedic ingredients for everyday wellness.",
		price: 799,
		badge: "Daily Wellness",
		tagline: "A refreshing start to your daily wellness ritual",
		quantity: "1 Litre",
		dosage: "Mix 30 ml with an equal amount of water and consume once daily before breakfast.",
		suitableFor: "Adults",
		images: [{ url: "/assets/img/p-3.jpeg" }, { url: "/assets/img/slider-1.png" }, { url: "/assets/img/bottle.png" }],
		ingredients: [{ name: "Amla", amount: "Primary juice", benefit: "A natural source of antioxidants", image: "/assets/img/story.png" }, { name: "Aloe Vera", amount: "Primary juice", benefit: "Supports digestive comfort", image: "/assets/img/ingredients.png" }],
		benefits: ["Supports antioxidant defenses", "Promotes digestive comfort", "Supports everyday immunity"],
		keyBenefits: [{ title: "Antioxidant Support", description: "Amla helps support natural antioxidant defenses." }, { title: "Digestive Comfort", description: "Aloe Vera supports a comfortable digestive routine." }, { title: "Daily Hydration", description: "An easy-to-mix addition to the morning routine." }],
		pricingTiers: [{ bottles: 1, duration: "1 Month", price: 449 }, { bottles: 2, duration: "2 Months", price: 799, originalPrice: 898, badge: "Best Value" }, { bottles: 3, duration: "3 Months", price: 1149, originalPrice: 1347 }],
		aboutParagraphs: ["Amla and Aloe Vera are widely used in traditional wellness routines across India.", "This balanced juice blend makes both botanicals easy to enjoy each morning."],
		benefitsIntro: "Two familiar botanicals work together to support digestion, antioxidant defenses, and daily wellness.",
		ingredientsIntro: "A straightforward blend centered on Amla and Aloe Vera juice.",
		howItWorks: "Taken consistently, the blend supports hydration, digestive comfort, and antioxidant intake.",
		productDetails: ["1 litre bottle", "Easy to dilute", "No added sugar", "Quality-tested ingredients"],
		usageLevels: [{ label: "Daily Serving", tablets: 30, frequency: "ml diluted with water before breakfast" }],
		testimonialsIntro: "Customers share how they use the juice in their morning routine.",
		testimonials: [{ name: "Nisha D.", role: "Verified customer", quote: "The taste is easy to drink when diluted, and the bottle lasts well.", image: "/assets/img/p-4.jpeg" }],
		relatedIds: ["liver-care-capsules", "ashwagandha-capsules"],
	},
];
